-- Create polls table
CREATE TABLE IF NOT EXISTS polls (
    PollID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    CreatedBy INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CreatedBy) REFERENCES USERS(UserID)
);

-- Create poll_options table
CREATE TABLE IF NOT EXISTS poll_options (
    OptionID INT PRIMARY KEY AUTO_INCREMENT,
    PollID INT NOT NULL,
    OptionText VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PollID) REFERENCES polls(PollID) ON DELETE CASCADE
);

-- Create poll_responses table
CREATE TABLE IF NOT EXISTS poll_responses (
    ResponseID INT PRIMARY KEY AUTO_INCREMENT,
    PollID INT NOT NULL,
    UserID INT NOT NULL,
    OptionID INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PollID) REFERENCES polls(PollID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    FOREIGN KEY (OptionID) REFERENCES poll_options(OptionID) ON DELETE CASCADE,
    UNIQUE KEY unique_vote (PollID, UserID)
); 